# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Logrus
owner: Pamela Mclean
email: pamela@logrus.ca

description: > # this means to ignore newlines until "baseurl:"
  The Logrus is the nexus of chaos. All reality exists as shadows resonating from the
  Logrus to the primal Pattern which is the nexus of all order.
baseurl:  # the subpath of your site, e.g. /blog
lang: "en"
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username:
github_username:
disqus_username:

# Build settings
markdown: kramdown
permalink: /:categories/:title/

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"

# May change this later, but for now:
collections:
    denizens:
        output: true
    recipes:
    rudanGaidhealach:
    sundayStories:
    songs:
    championsScenarios:
    
defaults:
  - scope:
      path: ""
      type: "denizens"
    values:
      layout: "denizens"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"


# Theme settings
compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all


sass:
  sass_dir: assets/_sass
  style: compressed


images: '/assets/images'
